# Configuration Netlify pour Ndiambour Location

[build]
  # Répertoire contenant les fichiers à déployer (laissez vide si c'est la racine)
  publish = "/"
  
  # Commande de build (laissez vide si pas de build nécessaire)
  command = ""

# Redirection pour les Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# En-têtes pour améliorer la sécurité et les performances
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com https://upload-widget.cloudinary.com https://res.cloudinary.com https://api.cloudinary.com https://www.gstatic.com https://firebasestorage.googleapis.com https://ndiambourloc.firebaseapp.com https://*.googleapis.com; img-src 'self' data: https://res.cloudinary.com https://firebasestorage.googleapis.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://upload-widget.cloudinary.com https://www.gstatic.com https://*.googleapis.com; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com;"

# Optimisations de cache
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
